// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: in_toto_attestation/predicates/scai/v0/scai.proto

package io.github.intoto.attestation.predicates.scai.v0;

public final class Scai {
  private Scai() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AttributeAssertionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:in_toto_attestation.predicates.scai.v0.AttributeAssertion)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string attribute = 1;</code>
     * @return The attribute.
     */
    java.lang.String getAttribute();
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string attribute = 1;</code>
     * @return The bytes for attribute.
     */
    com.google.protobuf.ByteString
        getAttributeBytes();

    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
     * @return Whether the target field is set.
     */
    boolean hasTarget();
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
     * @return The target.
     */
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getTarget();
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
     */
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getTargetOrBuilder();

    /**
     * <code>.google.protobuf.Struct conditions = 3;</code>
     * @return Whether the conditions field is set.
     */
    boolean hasConditions();
    /**
     * <code>.google.protobuf.Struct conditions = 3;</code>
     * @return The conditions.
     */
    com.google.protobuf.Struct getConditions();
    /**
     * <code>.google.protobuf.Struct conditions = 3;</code>
     */
    com.google.protobuf.StructOrBuilder getConditionsOrBuilder();

    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
     * @return Whether the evidence field is set.
     */
    boolean hasEvidence();
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
     * @return The evidence.
     */
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getEvidence();
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
     */
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getEvidenceOrBuilder();
  }
  /**
   * Protobuf type {@code in_toto_attestation.predicates.scai.v0.AttributeAssertion}
   */
  public static final class AttributeAssertion extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:in_toto_attestation.predicates.scai.v0.AttributeAssertion)
      AttributeAssertionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttributeAssertion.newBuilder() to construct.
    private AttributeAssertion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttributeAssertion() {
      attribute_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AttributeAssertion();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.class, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder.class);
    }

    private int bitField0_;
    public static final int ATTRIBUTE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object attribute_ = "";
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string attribute = 1;</code>
     * @return The attribute.
     */
    @java.lang.Override
    public java.lang.String getAttribute() {
      java.lang.Object ref = attribute_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        attribute_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>string attribute = 1;</code>
     * @return The bytes for attribute.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAttributeBytes() {
      java.lang.Object ref = attribute_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attribute_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_FIELD_NUMBER = 2;
    private io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor target_;
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
     * @return Whether the target field is set.
     */
    @java.lang.Override
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
     * @return The target.
     */
    @java.lang.Override
    public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getTarget() {
      return target_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : target_;
    }
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
     */
    @java.lang.Override
    public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getTargetOrBuilder() {
      return target_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : target_;
    }

    public static final int CONDITIONS_FIELD_NUMBER = 3;
    private com.google.protobuf.Struct conditions_;
    /**
     * <code>.google.protobuf.Struct conditions = 3;</code>
     * @return Whether the conditions field is set.
     */
    @java.lang.Override
    public boolean hasConditions() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Struct conditions = 3;</code>
     * @return The conditions.
     */
    @java.lang.Override
    public com.google.protobuf.Struct getConditions() {
      return conditions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : conditions_;
    }
    /**
     * <code>.google.protobuf.Struct conditions = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StructOrBuilder getConditionsOrBuilder() {
      return conditions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : conditions_;
    }

    public static final int EVIDENCE_FIELD_NUMBER = 4;
    private io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor evidence_;
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
     * @return Whether the evidence field is set.
     */
    @java.lang.Override
    public boolean hasEvidence() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
     * @return The evidence.
     */
    @java.lang.Override
    public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getEvidence() {
      return evidence_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : evidence_;
    }
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
     */
    @java.lang.Override
    public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getEvidenceOrBuilder() {
      return evidence_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : evidence_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(attribute_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, attribute_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getTarget());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getConditions());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(4, getEvidence());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(attribute_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, attribute_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTarget());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getConditions());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getEvidence());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion)) {
        return super.equals(obj);
      }
      io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion other = (io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion) obj;

      if (!getAttribute()
          .equals(other.getAttribute())) return false;
      if (hasTarget() != other.hasTarget()) return false;
      if (hasTarget()) {
        if (!getTarget()
            .equals(other.getTarget())) return false;
      }
      if (hasConditions() != other.hasConditions()) return false;
      if (hasConditions()) {
        if (!getConditions()
            .equals(other.getConditions())) return false;
      }
      if (hasEvidence() != other.hasEvidence()) return false;
      if (hasEvidence()) {
        if (!getEvidence()
            .equals(other.getEvidence())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ATTRIBUTE_FIELD_NUMBER;
      hash = (53 * hash) + getAttribute().hashCode();
      if (hasTarget()) {
        hash = (37 * hash) + TARGET_FIELD_NUMBER;
        hash = (53 * hash) + getTarget().hashCode();
      }
      if (hasConditions()) {
        hash = (37 * hash) + CONDITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getConditions().hashCode();
      }
      if (hasEvidence()) {
        hash = (37 * hash) + EVIDENCE_FIELD_NUMBER;
        hash = (53 * hash) + getEvidence().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code in_toto_attestation.predicates.scai.v0.AttributeAssertion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:in_toto_attestation.predicates.scai.v0.AttributeAssertion)
        io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.class, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder.class);
      }

      // Construct using io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTargetFieldBuilder();
          getConditionsFieldBuilder();
          getEvidenceFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        attribute_ = "";
        target_ = null;
        if (targetBuilder_ != null) {
          targetBuilder_.dispose();
          targetBuilder_ = null;
        }
        conditions_ = null;
        if (conditionsBuilder_ != null) {
          conditionsBuilder_.dispose();
          conditionsBuilder_ = null;
        }
        evidence_ = null;
        if (evidenceBuilder_ != null) {
          evidenceBuilder_.dispose();
          evidenceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_descriptor;
      }

      @java.lang.Override
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion getDefaultInstanceForType() {
        return io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion build() {
        io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion buildPartial() {
        io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion result = new io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.attribute_ = attribute_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.target_ = targetBuilder_ == null
              ? target_
              : targetBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.conditions_ = conditionsBuilder_ == null
              ? conditions_
              : conditionsBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.evidence_ = evidenceBuilder_ == null
              ? evidence_
              : evidenceBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion) {
          return mergeFrom((io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion other) {
        if (other == io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.getDefaultInstance()) return this;
        if (!other.getAttribute().isEmpty()) {
          attribute_ = other.attribute_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasTarget()) {
          mergeTarget(other.getTarget());
        }
        if (other.hasConditions()) {
          mergeConditions(other.getConditions());
        }
        if (other.hasEvidence()) {
          mergeEvidence(other.getEvidence());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                attribute_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getTargetFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getConditionsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getEvidenceFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object attribute_ = "";
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>string attribute = 1;</code>
       * @return The attribute.
       */
      public java.lang.String getAttribute() {
        java.lang.Object ref = attribute_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          attribute_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>string attribute = 1;</code>
       * @return The bytes for attribute.
       */
      public com.google.protobuf.ByteString
          getAttributeBytes() {
        java.lang.Object ref = attribute_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          attribute_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>string attribute = 1;</code>
       * @param value The attribute to set.
       * @return This builder for chaining.
       */
      public Builder setAttribute(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        attribute_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>string attribute = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttribute() {
        attribute_ = getDefaultInstance().getAttribute();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>string attribute = 1;</code>
       * @param value The bytes for attribute to set.
       * @return This builder for chaining.
       */
      public Builder setAttributeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        attribute_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor target_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> targetBuilder_;
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       * @return Whether the target field is set.
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       * @return The target.
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getTarget() {
        if (targetBuilder_ == null) {
          return target_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : target_;
        } else {
          return targetBuilder_.getMessage();
        }
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       */
      public Builder setTarget(io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          target_ = value;
        } else {
          targetBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       */
      public Builder setTarget(
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder builderForValue) {
        if (targetBuilder_ == null) {
          target_ = builderForValue.build();
        } else {
          targetBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       */
      public Builder mergeTarget(io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (targetBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            target_ != null &&
            target_ != io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance()) {
            getTargetBuilder().mergeFrom(value);
          } else {
            target_ = value;
          }
        } else {
          targetBuilder_.mergeFrom(value);
        }
        if (target_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000002);
        target_ = null;
        if (targetBuilder_ != null) {
          targetBuilder_.dispose();
          targetBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder getTargetBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTargetFieldBuilder().getBuilder();
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getTargetOrBuilder() {
        if (targetBuilder_ != null) {
          return targetBuilder_.getMessageOrBuilder();
        } else {
          return target_ == null ?
              io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : target_;
        }
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor target = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> 
          getTargetFieldBuilder() {
        if (targetBuilder_ == null) {
          targetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder>(
                  getTarget(),
                  getParentForChildren(),
                  isClean());
          target_ = null;
        }
        return targetBuilder_;
      }

      private com.google.protobuf.Struct conditions_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> conditionsBuilder_;
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       * @return Whether the conditions field is set.
       */
      public boolean hasConditions() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       * @return The conditions.
       */
      public com.google.protobuf.Struct getConditions() {
        if (conditionsBuilder_ == null) {
          return conditions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : conditions_;
        } else {
          return conditionsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       */
      public Builder setConditions(com.google.protobuf.Struct value) {
        if (conditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          conditions_ = value;
        } else {
          conditionsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       */
      public Builder setConditions(
          com.google.protobuf.Struct.Builder builderForValue) {
        if (conditionsBuilder_ == null) {
          conditions_ = builderForValue.build();
        } else {
          conditionsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       */
      public Builder mergeConditions(com.google.protobuf.Struct value) {
        if (conditionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            conditions_ != null &&
            conditions_ != com.google.protobuf.Struct.getDefaultInstance()) {
            getConditionsBuilder().mergeFrom(value);
          } else {
            conditions_ = value;
          }
        } else {
          conditionsBuilder_.mergeFrom(value);
        }
        if (conditions_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       */
      public Builder clearConditions() {
        bitField0_ = (bitField0_ & ~0x00000004);
        conditions_ = null;
        if (conditionsBuilder_ != null) {
          conditionsBuilder_.dispose();
          conditionsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       */
      public com.google.protobuf.Struct.Builder getConditionsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getConditionsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       */
      public com.google.protobuf.StructOrBuilder getConditionsOrBuilder() {
        if (conditionsBuilder_ != null) {
          return conditionsBuilder_.getMessageOrBuilder();
        } else {
          return conditions_ == null ?
              com.google.protobuf.Struct.getDefaultInstance() : conditions_;
        }
      }
      /**
       * <code>.google.protobuf.Struct conditions = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
          getConditionsFieldBuilder() {
        if (conditionsBuilder_ == null) {
          conditionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                  getConditions(),
                  getParentForChildren(),
                  isClean());
          conditions_ = null;
        }
        return conditionsBuilder_;
      }

      private io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor evidence_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> evidenceBuilder_;
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       * @return Whether the evidence field is set.
       */
      public boolean hasEvidence() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       * @return The evidence.
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getEvidence() {
        if (evidenceBuilder_ == null) {
          return evidence_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : evidence_;
        } else {
          return evidenceBuilder_.getMessage();
        }
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       */
      public Builder setEvidence(io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (evidenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          evidence_ = value;
        } else {
          evidenceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       */
      public Builder setEvidence(
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder builderForValue) {
        if (evidenceBuilder_ == null) {
          evidence_ = builderForValue.build();
        } else {
          evidenceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       */
      public Builder mergeEvidence(io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (evidenceBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            evidence_ != null &&
            evidence_ != io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance()) {
            getEvidenceBuilder().mergeFrom(value);
          } else {
            evidence_ = value;
          }
        } else {
          evidenceBuilder_.mergeFrom(value);
        }
        if (evidence_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       */
      public Builder clearEvidence() {
        bitField0_ = (bitField0_ & ~0x00000008);
        evidence_ = null;
        if (evidenceBuilder_ != null) {
          evidenceBuilder_.dispose();
          evidenceBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder getEvidenceBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getEvidenceFieldBuilder().getBuilder();
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getEvidenceOrBuilder() {
        if (evidenceBuilder_ != null) {
          return evidenceBuilder_.getMessageOrBuilder();
        } else {
          return evidence_ == null ?
              io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : evidence_;
        }
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor evidence = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> 
          getEvidenceFieldBuilder() {
        if (evidenceBuilder_ == null) {
          evidenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder>(
                  getEvidence(),
                  getParentForChildren(),
                  isClean());
          evidence_ = null;
        }
        return evidenceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:in_toto_attestation.predicates.scai.v0.AttributeAssertion)
    }

    // @@protoc_insertion_point(class_scope:in_toto_attestation.predicates.scai.v0.AttributeAssertion)
    private static final io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion();
    }

    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttributeAssertion>
        PARSER = new com.google.protobuf.AbstractParser<AttributeAssertion>() {
      @java.lang.Override
      public AttributeAssertion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AttributeAssertion> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttributeAssertion> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AttributeReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:in_toto_attestation.predicates.scai.v0.AttributeReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    java.util.List<io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion> 
        getAttributesList();
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion getAttributes(int index);
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    int getAttributesCount();
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    java.util.List<? extends io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder> 
        getAttributesOrBuilderList();
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder getAttributesOrBuilder(
        int index);

    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
     * @return Whether the producer field is set.
     */
    boolean hasProducer();
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
     * @return The producer.
     */
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getProducer();
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
     */
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getProducerOrBuilder();
  }
  /**
   * Protobuf type {@code in_toto_attestation.predicates.scai.v0.AttributeReport}
   */
  public static final class AttributeReport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:in_toto_attestation.predicates.scai.v0.AttributeReport)
      AttributeReportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttributeReport.newBuilder() to construct.
    private AttributeReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttributeReport() {
      attributes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AttributeReport();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport.class, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport.Builder.class);
    }

    private int bitField0_;
    public static final int ATTRIBUTES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion> attributes_;
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion> getAttributesList() {
      return attributes_;
    }
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    @java.lang.Override
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    @java.lang.Override
    public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
     */
    @java.lang.Override
    public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }

    public static final int PRODUCER_FIELD_NUMBER = 2;
    private io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor producer_;
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
     * @return Whether the producer field is set.
     */
    @java.lang.Override
    public boolean hasProducer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
     * @return The producer.
     */
    @java.lang.Override
    public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getProducer() {
      return producer_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : producer_;
    }
    /**
     * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
     */
    @java.lang.Override
    public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getProducerOrBuilder() {
      return producer_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : producer_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(1, attributes_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getProducer());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, attributes_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getProducer());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport)) {
        return super.equals(obj);
      }
      io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport other = (io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport) obj;

      if (!getAttributesList()
          .equals(other.getAttributesList())) return false;
      if (hasProducer() != other.hasProducer()) return false;
      if (hasProducer()) {
        if (!getProducer()
            .equals(other.getProducer())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAttributesCount() > 0) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + getAttributesList().hashCode();
      }
      if (hasProducer()) {
        hash = (37 * hash) + PRODUCER_FIELD_NUMBER;
        hash = (53 * hash) + getProducer().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code in_toto_attestation.predicates.scai.v0.AttributeReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:in_toto_attestation.predicates.scai.v0.AttributeReport)
        io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport.class, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport.Builder.class);
      }

      // Construct using io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
          getProducerFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
        } else {
          attributes_ = null;
          attributesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        producer_ = null;
        if (producerBuilder_ != null) {
          producerBuilder_.dispose();
          producerBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.intoto.attestation.predicates.scai.v0.Scai.internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_descriptor;
      }

      @java.lang.Override
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport getDefaultInstanceForType() {
        return io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport build() {
        io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport buildPartial() {
        io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport result = new io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport result) {
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
      }

      private void buildPartial0(io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.producer_ = producerBuilder_ == null
              ? producer_
              : producerBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport) {
          return mergeFrom((io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport other) {
        if (other == io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport.getDefaultInstance()) return this;
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        if (other.hasProducer()) {
          mergeProducer(other.getProducer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion m =
                    input.readMessage(
                        io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.parser(),
                        extensionRegistry);
                if (attributesBuilder_ == null) {
                  ensureAttributesIsMutable();
                  attributes_.add(m);
                } else {
                  attributesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getProducerFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          attributes_ = new java.util.ArrayList<io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion>(attributes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder> attributesBuilder_;

      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public java.util.List<io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder setAttributes(
          int index, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder setAttributes(
          int index, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder addAttributes(io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder addAttributes(
          int index, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder addAttributes(
          io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder addAttributes(
          int index, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder addAllAttributes(
          java.lang.Iterable<? extends io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public java.util.List<? extends io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.getDefaultInstance());
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.getDefaultInstance());
      }
      /**
       * <code>repeated .in_toto_attestation.predicates.scai.v0.AttributeAssertion attributes = 1;</code>
       */
      public java.util.List<io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertion.Builder, io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeAssertionOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }

      private io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor producer_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> producerBuilder_;
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       * @return Whether the producer field is set.
       */
      public boolean hasProducer() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       * @return The producer.
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getProducer() {
        if (producerBuilder_ == null) {
          return producer_ == null ? io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : producer_;
        } else {
          return producerBuilder_.getMessage();
        }
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       */
      public Builder setProducer(io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (producerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          producer_ = value;
        } else {
          producerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       */
      public Builder setProducer(
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder builderForValue) {
        if (producerBuilder_ == null) {
          producer_ = builderForValue.build();
        } else {
          producerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       */
      public Builder mergeProducer(io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (producerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            producer_ != null &&
            producer_ != io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance()) {
            getProducerBuilder().mergeFrom(value);
          } else {
            producer_ = value;
          }
        } else {
          producerBuilder_.mergeFrom(value);
        }
        if (producer_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       */
      public Builder clearProducer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        producer_ = null;
        if (producerBuilder_ != null) {
          producerBuilder_.dispose();
          producerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder getProducerBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getProducerFieldBuilder().getBuilder();
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getProducerOrBuilder() {
        if (producerBuilder_ != null) {
          return producerBuilder_.getMessageOrBuilder();
        } else {
          return producer_ == null ?
              io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance() : producer_;
        }
      }
      /**
       * <code>.in_toto_attestation.v1.ResourceDescriptor producer = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> 
          getProducerFieldBuilder() {
        if (producerBuilder_ == null) {
          producerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder>(
                  getProducer(),
                  getParentForChildren(),
                  isClean());
          producer_ = null;
        }
        return producerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:in_toto_attestation.predicates.scai.v0.AttributeReport)
    }

    // @@protoc_insertion_point(class_scope:in_toto_attestation.predicates.scai.v0.AttributeReport)
    private static final io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport();
    }

    public static io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttributeReport>
        PARSER = new com.google.protobuf.AbstractParser<AttributeReport>() {
      @java.lang.Override
      public AttributeReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AttributeReport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttributeReport> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.intoto.attestation.predicates.scai.v0.Scai.AttributeReport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1in_toto_attestation/predicates/scai/v0" +
      "/scai.proto\022&in_toto_attestation.predica" +
      "tes.scai.v0\032\034google/protobuf/struct.prot" +
      "o\0320in_toto_attestation/v1/resource_descr" +
      "iptor.proto\"\316\001\n\022AttributeAssertion\022\021\n\tat" +
      "tribute\030\001 \001(\t\022:\n\006target\030\002 \001(\0132*.in_toto_" +
      "attestation.v1.ResourceDescriptor\022+\n\ncon" +
      "ditions\030\003 \001(\0132\027.google.protobuf.Struct\022<" +
      "\n\010evidence\030\004 \001(\0132*.in_toto_attestation.v" +
      "1.ResourceDescriptor\"\237\001\n\017AttributeReport" +
      "\022N\n\nattributes\030\001 \003(\0132:.in_toto_attestati" +
      "on.predicates.scai.v0.AttributeAssertion" +
      "\022<\n\010producer\030\002 \001(\0132*.in_toto_attestation" +
      ".v1.ResourceDescriptorBg\n/io.github.into" +
      "to.attestation.predicates.scai.v0Z4githu" +
      "b.com/in-toto/attestation/go/predicates/" +
      "scai/v0b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.getDescriptor(),
        });
    internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_in_toto_attestation_predicates_scai_v0_AttributeAssertion_descriptor,
        new java.lang.String[] { "Attribute", "Target", "Conditions", "Evidence", });
    internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_in_toto_attestation_predicates_scai_v0_AttributeReport_descriptor,
        new java.lang.String[] { "Attributes", "Producer", });
    com.google.protobuf.StructProto.getDescriptor();
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
