# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: in_toto_attestation/predicates/link/v0/link.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf

from .... import v1 as ___v1__


@dataclass(eq=False, repr=False)
class Link(betterproto.Message):
    name: str = betterproto.string_field(1)
    command: List[str] = betterproto.string_field(2)
    materials: List["___v1__.ResourceDescriptor"] = betterproto.message_field(3)
    byproducts: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(4)
    environment: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(5)
