# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: in_toto_attestation/v1/resource_descriptor.proto, in_toto_attestation/v1/statement.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    List,
)

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf


@dataclass(eq=False, repr=False)
class ResourceDescriptor(betterproto.Message):
    """
    Proto representation of the in-toto v1 ResourceDescriptor.
    https://github.com/in-
    toto/attestation/blob/main/spec/v1/resource_descriptor.md Validation of all
    fields is left to the users of this proto.
    """

    name: str = betterproto.string_field(1)
    uri: str = betterproto.string_field(2)
    digest: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    content: bytes = betterproto.bytes_field(4)
    download_location: str = betterproto.string_field(5)
    media_type: str = betterproto.string_field(6)
    annotations: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(7)
    """
    Per the Struct protobuf spec, this type corresponds to a JSON Object, which
    is truly a map<string, Value> under the hood. So, the Struct a) is still
    consistent with our specification for the `annotations` field, and b) has
    native support in some language bindings making their use easier in
    implementations. See:
    https://pkg.go.dev/google.golang.org/protobuf/types/known/structpb#Struct
    """


@dataclass(eq=False, repr=False)
class Statement(betterproto.Message):
    """
    Proto representation of the in-toto v1 Statement. https://github.com/in-
    toto/attestation/tree/main/spec/v1 Validation of all fields is left to the
    users of this proto.
    """

    type: str = betterproto.string_field(1)
    """Expected to always be "https://in-toto.io/Statement/v1"""

    subject: List["ResourceDescriptor"] = betterproto.message_field(2)
    predicate_type: str = betterproto.string_field(3)
    predicate: "betterproto_lib_google_protobuf.Struct" = betterproto.message_field(4)
