// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 24.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `in_toto_attestation/predicates/svr/v0.1/svr.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SimpleVerificationResult {
    // message fields
    // @@protoc_insertion_point(field:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.verifier)
    pub verifier: ::protobuf::MessageField<simple_verification_result::Verifier>,
    // @@protoc_insertion_point(field:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.time_created)
    pub time_created: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.properties)
    pub properties: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SimpleVerificationResult {
    fn default() -> &'a SimpleVerificationResult {
        <SimpleVerificationResult as ::protobuf::Message>::default_instance()
    }
}

impl SimpleVerificationResult {
    pub fn new() -> SimpleVerificationResult {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, simple_verification_result::Verifier>(
            "verifier",
            |m: &SimpleVerificationResult| { &m.verifier },
            |m: &mut SimpleVerificationResult| { &mut m.verifier },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "time_created",
            |m: &SimpleVerificationResult| { &m.time_created },
            |m: &mut SimpleVerificationResult| { &mut m.time_created },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "properties",
            |m: &SimpleVerificationResult| { &m.properties },
            |m: &mut SimpleVerificationResult| { &mut m.properties },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SimpleVerificationResult>(
            "SimpleVerificationResult",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SimpleVerificationResult {
    const NAME: &'static str = "SimpleVerificationResult";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.verifier)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.time_created)?;
                },
                26 => {
                    self.properties.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.verifier.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.time_created.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.properties {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.verifier.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.time_created.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        for v in &self.properties {
            os.write_string(3, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SimpleVerificationResult {
        SimpleVerificationResult::new()
    }

    fn clear(&mut self) {
        self.verifier.clear();
        self.time_created.clear();
        self.properties.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SimpleVerificationResult {
        static instance: SimpleVerificationResult = SimpleVerificationResult {
            verifier: ::protobuf::MessageField::none(),
            time_created: ::protobuf::MessageField::none(),
            properties: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SimpleVerificationResult {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SimpleVerificationResult").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SimpleVerificationResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SimpleVerificationResult {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `SimpleVerificationResult`
pub mod simple_verification_result {
    // @@protoc_insertion_point(message:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.Verifier)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Verifier {
        // message fields
        // @@protoc_insertion_point(field:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.Verifier.id)
        pub id: ::std::string::String,
        // @@protoc_insertion_point(field:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.Verifier.policy)
        pub policy: ::protobuf::MessageField<::protobuf::well_known_types::any::Any>,
        // special fields
        // @@protoc_insertion_point(special_field:in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.Verifier.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Verifier {
        fn default() -> &'a Verifier {
            <Verifier as ::protobuf::Message>::default_instance()
        }
    }

    impl Verifier {
        pub fn new() -> Verifier {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "id",
                |m: &Verifier| { &m.id },
                |m: &mut Verifier| { &mut m.id },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::any::Any>(
                "policy",
                |m: &Verifier| { &m.policy },
                |m: &mut Verifier| { &mut m.policy },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Verifier>(
                "SimpleVerificationResult.Verifier",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for Verifier {
        const NAME: &'static str = "Verifier";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.id = is.read_string()?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.policy)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.id.is_empty() {
                my_size += ::protobuf::rt::string_size(1, &self.id);
            }
            if let Some(v) = self.policy.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.id.is_empty() {
                os.write_string(1, &self.id)?;
            }
            if let Some(v) = self.policy.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Verifier {
            Verifier::new()
        }

        fn clear(&mut self) {
            self.id.clear();
            self.policy.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Verifier {
            static instance: Verifier = Verifier {
                id: ::std::string::String::new(),
                policy: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for Verifier {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("SimpleVerificationResult.Verifier").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for Verifier {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for Verifier {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n1in_toto_attestation/predicates/svr/v0.1/svr.proto\x12'in_toto_attesta\
    tion.predicates.svr.v0_1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19g\
    oogle/protobuf/any.proto\"\xbb\x02\n\x18SimpleVerificationResult\x12f\n\
    \x08verifier\x18\x01\x20\x01(\x0b2J.in_toto_attestation.predicates.svr.v\
    0_1.SimpleVerificationResult.VerifierR\x08verifier\x12=\n\x0ctime_create\
    d\x18\x02\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\x0btimeCreated\
    \x12\x1e\n\nproperties\x18\x03\x20\x03(\tR\nproperties\x1aX\n\x08Verifie\
    r\x12\x0e\n\x02id\x18\x01\x20\x01(\tR\x02id\x121\n\x06policy\x18\x02\x20\
    \x01(\x0b2\x14.google.protobuf.AnyH\0R\x06policy\x88\x01\x01B\t\n\x07_po\
    licyBg\n/io.github.intoto.attestation.predicates.svr.v01Z4github.com/in-\
    toto/attestation/go/predicates/svr/v01b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::any::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(SimpleVerificationResult::generated_message_descriptor_data());
            messages.push(simple_verification_result::Verifier::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
