# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: in_toto_attestation/predicates/provenance/v1/provenance.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    Dict,
    List,
)

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf

from .... import v1 as ___v1__


@dataclass(eq=False, repr=False)
class Provenance(betterproto.Message):
    """
    Proto representation of predicate type https://slsa.dev/provenance/v1
    Validation of all fields is left to the users of this proto.
    """

    build_definition: "BuildDefinition" = betterproto.message_field(1)
    run_details: "RunDetails" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class BuildDefinition(betterproto.Message):
    build_type: str = betterproto.string_field(1)
    external_parameters: "betterproto_lib_google_protobuf.Struct" = (
        betterproto.message_field(2)
    )
    internal_parameters: "betterproto_lib_google_protobuf.Struct" = (
        betterproto.message_field(3)
    )
    resolved_dependencies: List["___v1__.ResourceDescriptor"] = (
        betterproto.message_field(4)
    )


@dataclass(eq=False, repr=False)
class RunDetails(betterproto.Message):
    builder: "Builder" = betterproto.message_field(1)
    metadata: "BuildMetadata" = betterproto.message_field(2)
    byproducts: List["___v1__.ResourceDescriptor"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class Builder(betterproto.Message):
    id: str = betterproto.string_field(1)
    version: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    builder_dependencies: List["___v1__.ResourceDescriptor"] = (
        betterproto.message_field(3)
    )


@dataclass(eq=False, repr=False)
class BuildMetadata(betterproto.Message):
    invocation_id: str = betterproto.string_field(1)
    started_on: datetime = betterproto.message_field(2)
    finished_on: datetime = betterproto.message_field(3)
