# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predicates/vsa/vsa.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='predicates/vsa/vsa.proto',
  package='io.in_toto.attestation.predicates',
  syntax='proto3',
  serialized_options=b'Z1github.com/in-toto/attestation/go/spec/predicates',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18predicates/vsa/vsa.proto\x12!io.in_toto.attestation.predicates\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x08\n\x16VerificationSummaryV02\x12T\n\x08verifier\x18\x01 \x01(\x0b\x32\x42.io.in_toto.attestation.predicates.VerificationSummaryV02.Verifier\x12?\n\x0ctimeVerified\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\rtime_verified\x12!\n\x0bresourceUri\x18\x03 \x01(\tR\x0cresource_uri\x12P\n\x06policy\x18\x04 \x01(\x0b\x32@.io.in_toto.attestation.predicates.VerificationSummaryV02.Policy\x12y\n\x11inputAttestations\x18\x05 \x03(\x0b\x32J.io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestationR\x12input_attestations\x12/\n\x12verificationResult\x18\x06 \x01(\tR\x13verification_result\x12!\n\x0bpolicyLevel\x18\x07 \x01(\tR\x0cpolicy_level\x12|\n\x10\x64\x65pendencyLevels\x18\x08 \x03(\x0b\x32O.io.in_toto.attestation.predicates.VerificationSummaryV02.DependencyLevelsEntryR\x11\x64\x65pendency_levels\x1a\x16\n\x08Verifier\x12\n\n\x02id\x18\x01 \x01(\t\x1a\xa2\x01\n\x06Policy\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\\\n\x06\x64igest\x18\x02 \x03(\x0b\x32L.io.in_toto.attestation.predicates.VerificationSummaryV02.Policy.DigestEntry\x1a-\n\x0b\x44igestEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\xb6\x01\n\x10InputAttestation\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x66\n\x06\x64igest\x18\x02 \x03(\x0b\x32V.io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation.DigestEntry\x1a-\n\x0b\x44igestEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x37\n\x15\x44\x65pendencyLevelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x42\x33Z1github.com/in-toto/attestation/go/spec/predicatesb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_VERIFICATIONSUMMARYV02_VERIFIER = _descriptor.Descriptor(
  name='Verifier',
  full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.Verifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.Verifier.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=746,
)

_VERIFICATIONSUMMARYV02_POLICY_DIGESTENTRY = _descriptor.Descriptor(
  name='DigestEntry',
  full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.Policy.DigestEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.Policy.DigestEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.Policy.DigestEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=866,
  serialized_end=911,
)

_VERIFICATIONSUMMARYV02_POLICY = _descriptor.Descriptor(
  name='Policy',
  full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.Policy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.Policy.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='digest', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.Policy.digest', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VERIFICATIONSUMMARYV02_POLICY_DIGESTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=749,
  serialized_end=911,
)

_VERIFICATIONSUMMARYV02_INPUTATTESTATION_DIGESTENTRY = _descriptor.Descriptor(
  name='DigestEntry',
  full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation.DigestEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation.DigestEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation.DigestEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=866,
  serialized_end=911,
)

_VERIFICATIONSUMMARYV02_INPUTATTESTATION = _descriptor.Descriptor(
  name='InputAttestation',
  full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='digest', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation.digest', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VERIFICATIONSUMMARYV02_INPUTATTESTATION_DIGESTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=914,
  serialized_end=1096,
)

_VERIFICATIONSUMMARYV02_DEPENDENCYLEVELSENTRY = _descriptor.Descriptor(
  name='DependencyLevelsEntry',
  full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.DependencyLevelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.DependencyLevelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.DependencyLevelsEntry.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1098,
  serialized_end=1153,
)

_VERIFICATIONSUMMARYV02 = _descriptor.Descriptor(
  name='VerificationSummaryV02',
  full_name='io.in_toto.attestation.predicates.VerificationSummaryV02',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='verifier', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.verifier', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeVerified', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.timeVerified', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='time_verified', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resourceUri', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.resourceUri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='resource_uri', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='policy', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.policy', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inputAttestations', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.inputAttestations', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='input_attestations', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verificationResult', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.verificationResult', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='verification_result', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='policyLevel', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.policyLevel', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='policy_level', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dependencyLevels', full_name='io.in_toto.attestation.predicates.VerificationSummaryV02.dependencyLevels', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='dependency_levels', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VERIFICATIONSUMMARYV02_VERIFIER, _VERIFICATIONSUMMARYV02_POLICY, _VERIFICATIONSUMMARYV02_INPUTATTESTATION, _VERIFICATIONSUMMARYV02_DEPENDENCYLEVELSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=1153,
)

_VERIFICATIONSUMMARYV02_VERIFIER.containing_type = _VERIFICATIONSUMMARYV02
_VERIFICATIONSUMMARYV02_POLICY_DIGESTENTRY.containing_type = _VERIFICATIONSUMMARYV02_POLICY
_VERIFICATIONSUMMARYV02_POLICY.fields_by_name['digest'].message_type = _VERIFICATIONSUMMARYV02_POLICY_DIGESTENTRY
_VERIFICATIONSUMMARYV02_POLICY.containing_type = _VERIFICATIONSUMMARYV02
_VERIFICATIONSUMMARYV02_INPUTATTESTATION_DIGESTENTRY.containing_type = _VERIFICATIONSUMMARYV02_INPUTATTESTATION
_VERIFICATIONSUMMARYV02_INPUTATTESTATION.fields_by_name['digest'].message_type = _VERIFICATIONSUMMARYV02_INPUTATTESTATION_DIGESTENTRY
_VERIFICATIONSUMMARYV02_INPUTATTESTATION.containing_type = _VERIFICATIONSUMMARYV02
_VERIFICATIONSUMMARYV02_DEPENDENCYLEVELSENTRY.containing_type = _VERIFICATIONSUMMARYV02
_VERIFICATIONSUMMARYV02.fields_by_name['verifier'].message_type = _VERIFICATIONSUMMARYV02_VERIFIER
_VERIFICATIONSUMMARYV02.fields_by_name['timeVerified'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_VERIFICATIONSUMMARYV02.fields_by_name['policy'].message_type = _VERIFICATIONSUMMARYV02_POLICY
_VERIFICATIONSUMMARYV02.fields_by_name['inputAttestations'].message_type = _VERIFICATIONSUMMARYV02_INPUTATTESTATION
_VERIFICATIONSUMMARYV02.fields_by_name['dependencyLevels'].message_type = _VERIFICATIONSUMMARYV02_DEPENDENCYLEVELSENTRY
DESCRIPTOR.message_types_by_name['VerificationSummaryV02'] = _VERIFICATIONSUMMARYV02
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerificationSummaryV02 = _reflection.GeneratedProtocolMessageType('VerificationSummaryV02', (_message.Message,), {

  'Verifier' : _reflection.GeneratedProtocolMessageType('Verifier', (_message.Message,), {
    'DESCRIPTOR' : _VERIFICATIONSUMMARYV02_VERIFIER,
    '__module__' : 'predicates.vsa.vsa_pb2'
    # @@protoc_insertion_point(class_scope:io.in_toto.attestation.predicates.VerificationSummaryV02.Verifier)
    })
  ,

  'Policy' : _reflection.GeneratedProtocolMessageType('Policy', (_message.Message,), {

    'DigestEntry' : _reflection.GeneratedProtocolMessageType('DigestEntry', (_message.Message,), {
      'DESCRIPTOR' : _VERIFICATIONSUMMARYV02_POLICY_DIGESTENTRY,
      '__module__' : 'predicates.vsa.vsa_pb2'
      # @@protoc_insertion_point(class_scope:io.in_toto.attestation.predicates.VerificationSummaryV02.Policy.DigestEntry)
      })
    ,
    'DESCRIPTOR' : _VERIFICATIONSUMMARYV02_POLICY,
    '__module__' : 'predicates.vsa.vsa_pb2'
    # @@protoc_insertion_point(class_scope:io.in_toto.attestation.predicates.VerificationSummaryV02.Policy)
    })
  ,

  'InputAttestation' : _reflection.GeneratedProtocolMessageType('InputAttestation', (_message.Message,), {

    'DigestEntry' : _reflection.GeneratedProtocolMessageType('DigestEntry', (_message.Message,), {
      'DESCRIPTOR' : _VERIFICATIONSUMMARYV02_INPUTATTESTATION_DIGESTENTRY,
      '__module__' : 'predicates.vsa.vsa_pb2'
      # @@protoc_insertion_point(class_scope:io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation.DigestEntry)
      })
    ,
    'DESCRIPTOR' : _VERIFICATIONSUMMARYV02_INPUTATTESTATION,
    '__module__' : 'predicates.vsa.vsa_pb2'
    # @@protoc_insertion_point(class_scope:io.in_toto.attestation.predicates.VerificationSummaryV02.InputAttestation)
    })
  ,

  'DependencyLevelsEntry' : _reflection.GeneratedProtocolMessageType('DependencyLevelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _VERIFICATIONSUMMARYV02_DEPENDENCYLEVELSENTRY,
    '__module__' : 'predicates.vsa.vsa_pb2'
    # @@protoc_insertion_point(class_scope:io.in_toto.attestation.predicates.VerificationSummaryV02.DependencyLevelsEntry)
    })
  ,
  'DESCRIPTOR' : _VERIFICATIONSUMMARYV02,
  '__module__' : 'predicates.vsa.vsa_pb2'
  # @@protoc_insertion_point(class_scope:io.in_toto.attestation.predicates.VerificationSummaryV02)
  })
_sym_db.RegisterMessage(VerificationSummaryV02)
_sym_db.RegisterMessage(VerificationSummaryV02.Verifier)
_sym_db.RegisterMessage(VerificationSummaryV02.Policy)
_sym_db.RegisterMessage(VerificationSummaryV02.Policy.DigestEntry)
_sym_db.RegisterMessage(VerificationSummaryV02.InputAttestation)
_sym_db.RegisterMessage(VerificationSummaryV02.InputAttestation.DigestEntry)
_sym_db.RegisterMessage(VerificationSummaryV02.DependencyLevelsEntry)


DESCRIPTOR._options = None
_VERIFICATIONSUMMARYV02_POLICY_DIGESTENTRY._options = None
_VERIFICATIONSUMMARYV02_INPUTATTESTATION_DIGESTENTRY._options = None
_VERIFICATIONSUMMARYV02_DEPENDENCYLEVELSENTRY._options = None
# @@protoc_insertion_point(module_scope)
