# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: in_toto_attestation/predicates/vsa/v0/vsa.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    Dict,
    List,
)

import betterproto


@dataclass(eq=False, repr=False)
class VerificationSummary(betterproto.Message):
    """
    Proto representation of predicate type
    https://slsa.dev/verification_summary/v0.2 Validation of all fields is left
    to the users of this proto.
    """

    verifier: "VerificationSummaryVerifier" = betterproto.message_field(1)
    time_verified: datetime = betterproto.message_field(2)
    resource_uri: str = betterproto.string_field(3)
    policy: "VerificationSummaryPolicy" = betterproto.message_field(4)
    input_attestations: List["VerificationSummaryInputAttestation"] = (
        betterproto.message_field(5)
    )
    verification_result: str = betterproto.string_field(6)
    policy_level: str = betterproto.string_field(7)
    dependency_levels: Dict[str, int] = betterproto.map_field(
        8, betterproto.TYPE_STRING, betterproto.TYPE_UINT64
    )


@dataclass(eq=False, repr=False)
class VerificationSummaryVerifier(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class VerificationSummaryPolicy(betterproto.Message):
    uri: str = betterproto.string_field(1)
    digest: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class VerificationSummaryInputAttestation(betterproto.Message):
    uri: str = betterproto.string_field(1)
    digest: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
