// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: in_toto_attestation/v1/statement.proto

package io.github.intoto.attestation.v1;

public final class StatementOuterClass {
  private StatementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StatementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:in_toto_attestation.v1.Statement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Expected to always be "https://in-toto.io/Statement/v1"
     * </pre>
     *
     * <code>string type = 1 [json_name = "_type"];</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     * Expected to always be "https://in-toto.io/Statement/v1"
     * </pre>
     *
     * <code>string type = 1 [json_name = "_type"];</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    java.util.List<io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor> 
        getSubjectList();
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getSubject(int index);
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    int getSubjectCount();
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    java.util.List<? extends io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> 
        getSubjectOrBuilderList();
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getSubjectOrBuilder(
        int index);

    /**
     * <code>string predicate_type = 3;</code>
     * @return The predicateType.
     */
    java.lang.String getPredicateType();
    /**
     * <code>string predicate_type = 3;</code>
     * @return The bytes for predicateType.
     */
    com.google.protobuf.ByteString
        getPredicateTypeBytes();

    /**
     * <code>.google.protobuf.Struct predicate = 4;</code>
     * @return Whether the predicate field is set.
     */
    boolean hasPredicate();
    /**
     * <code>.google.protobuf.Struct predicate = 4;</code>
     * @return The predicate.
     */
    com.google.protobuf.Struct getPredicate();
    /**
     * <code>.google.protobuf.Struct predicate = 4;</code>
     */
    com.google.protobuf.StructOrBuilder getPredicateOrBuilder();
  }
  /**
   * <pre>
   * Proto representation of the in-toto v1 Statement.
   * https://github.com/in-toto/attestation/tree/main/spec/v1
   * Validation of all fields is left to the users of this proto.
   * </pre>
   *
   * Protobuf type {@code in_toto_attestation.v1.Statement}
   */
  public static final class Statement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:in_toto_attestation.v1.Statement)
      StatementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Statement.newBuilder() to construct.
    private Statement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Statement() {
      type_ = "";
      subject_ = java.util.Collections.emptyList();
      predicateType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Statement();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.intoto.attestation.v1.StatementOuterClass.internal_static_in_toto_attestation_v1_Statement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.intoto.attestation.v1.StatementOuterClass.internal_static_in_toto_attestation_v1_Statement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.intoto.attestation.v1.StatementOuterClass.Statement.class, io.github.intoto.attestation.v1.StatementOuterClass.Statement.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <pre>
     * Expected to always be "https://in-toto.io/Statement/v1"
     * </pre>
     *
     * <code>string type = 1 [json_name = "_type"];</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Expected to always be "https://in-toto.io/Statement/v1"
     * </pre>
     *
     * <code>string type = 1 [json_name = "_type"];</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor> subject_;
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor> getSubjectList() {
      return subject_;
    }
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> 
        getSubjectOrBuilderList() {
      return subject_;
    }
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    @java.lang.Override
    public int getSubjectCount() {
      return subject_.size();
    }
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    @java.lang.Override
    public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getSubject(int index) {
      return subject_.get(index);
    }
    /**
     * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
     */
    @java.lang.Override
    public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getSubjectOrBuilder(
        int index) {
      return subject_.get(index);
    }

    public static final int PREDICATE_TYPE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object predicateType_ = "";
    /**
     * <code>string predicate_type = 3;</code>
     * @return The predicateType.
     */
    @java.lang.Override
    public java.lang.String getPredicateType() {
      java.lang.Object ref = predicateType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        predicateType_ = s;
        return s;
      }
    }
    /**
     * <code>string predicate_type = 3;</code>
     * @return The bytes for predicateType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPredicateTypeBytes() {
      java.lang.Object ref = predicateType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        predicateType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREDICATE_FIELD_NUMBER = 4;
    private com.google.protobuf.Struct predicate_;
    /**
     * <code>.google.protobuf.Struct predicate = 4;</code>
     * @return Whether the predicate field is set.
     */
    @java.lang.Override
    public boolean hasPredicate() {
      return predicate_ != null;
    }
    /**
     * <code>.google.protobuf.Struct predicate = 4;</code>
     * @return The predicate.
     */
    @java.lang.Override
    public com.google.protobuf.Struct getPredicate() {
      return predicate_ == null ? com.google.protobuf.Struct.getDefaultInstance() : predicate_;
    }
    /**
     * <code>.google.protobuf.Struct predicate = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StructOrBuilder getPredicateOrBuilder() {
      return predicate_ == null ? com.google.protobuf.Struct.getDefaultInstance() : predicate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      for (int i = 0; i < subject_.size(); i++) {
        output.writeMessage(2, subject_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(predicateType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, predicateType_);
      }
      if (predicate_ != null) {
        output.writeMessage(4, getPredicate());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      for (int i = 0; i < subject_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, subject_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(predicateType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, predicateType_);
      }
      if (predicate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPredicate());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.intoto.attestation.v1.StatementOuterClass.Statement)) {
        return super.equals(obj);
      }
      io.github.intoto.attestation.v1.StatementOuterClass.Statement other = (io.github.intoto.attestation.v1.StatementOuterClass.Statement) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getSubjectList()
          .equals(other.getSubjectList())) return false;
      if (!getPredicateType()
          .equals(other.getPredicateType())) return false;
      if (hasPredicate() != other.hasPredicate()) return false;
      if (hasPredicate()) {
        if (!getPredicate()
            .equals(other.getPredicate())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (getSubjectCount() > 0) {
        hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getSubjectList().hashCode();
      }
      hash = (37 * hash) + PREDICATE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPredicateType().hashCode();
      if (hasPredicate()) {
        hash = (37 * hash) + PREDICATE_FIELD_NUMBER;
        hash = (53 * hash) + getPredicate().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.intoto.attestation.v1.StatementOuterClass.Statement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Proto representation of the in-toto v1 Statement.
     * https://github.com/in-toto/attestation/tree/main/spec/v1
     * Validation of all fields is left to the users of this proto.
     * </pre>
     *
     * Protobuf type {@code in_toto_attestation.v1.Statement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:in_toto_attestation.v1.Statement)
        io.github.intoto.attestation.v1.StatementOuterClass.StatementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.intoto.attestation.v1.StatementOuterClass.internal_static_in_toto_attestation_v1_Statement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.intoto.attestation.v1.StatementOuterClass.internal_static_in_toto_attestation_v1_Statement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.intoto.attestation.v1.StatementOuterClass.Statement.class, io.github.intoto.attestation.v1.StatementOuterClass.Statement.Builder.class);
      }

      // Construct using io.github.intoto.attestation.v1.StatementOuterClass.Statement.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        if (subjectBuilder_ == null) {
          subject_ = java.util.Collections.emptyList();
        } else {
          subject_ = null;
          subjectBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        predicateType_ = "";
        predicate_ = null;
        if (predicateBuilder_ != null) {
          predicateBuilder_.dispose();
          predicateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.intoto.attestation.v1.StatementOuterClass.internal_static_in_toto_attestation_v1_Statement_descriptor;
      }

      @java.lang.Override
      public io.github.intoto.attestation.v1.StatementOuterClass.Statement getDefaultInstanceForType() {
        return io.github.intoto.attestation.v1.StatementOuterClass.Statement.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.intoto.attestation.v1.StatementOuterClass.Statement build() {
        io.github.intoto.attestation.v1.StatementOuterClass.Statement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.intoto.attestation.v1.StatementOuterClass.Statement buildPartial() {
        io.github.intoto.attestation.v1.StatementOuterClass.Statement result = new io.github.intoto.attestation.v1.StatementOuterClass.Statement(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(io.github.intoto.attestation.v1.StatementOuterClass.Statement result) {
        if (subjectBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            subject_ = java.util.Collections.unmodifiableList(subject_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.subject_ = subject_;
        } else {
          result.subject_ = subjectBuilder_.build();
        }
      }

      private void buildPartial0(io.github.intoto.attestation.v1.StatementOuterClass.Statement result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.predicateType_ = predicateType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.predicate_ = predicateBuilder_ == null
              ? predicate_
              : predicateBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.intoto.attestation.v1.StatementOuterClass.Statement) {
          return mergeFrom((io.github.intoto.attestation.v1.StatementOuterClass.Statement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.intoto.attestation.v1.StatementOuterClass.Statement other) {
        if (other == io.github.intoto.attestation.v1.StatementOuterClass.Statement.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (subjectBuilder_ == null) {
          if (!other.subject_.isEmpty()) {
            if (subject_.isEmpty()) {
              subject_ = other.subject_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSubjectIsMutable();
              subject_.addAll(other.subject_);
            }
            onChanged();
          }
        } else {
          if (!other.subject_.isEmpty()) {
            if (subjectBuilder_.isEmpty()) {
              subjectBuilder_.dispose();
              subjectBuilder_ = null;
              subject_ = other.subject_;
              bitField0_ = (bitField0_ & ~0x00000002);
              subjectBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubjectFieldBuilder() : null;
            } else {
              subjectBuilder_.addAllMessages(other.subject_);
            }
          }
        }
        if (!other.getPredicateType().isEmpty()) {
          predicateType_ = other.predicateType_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasPredicate()) {
          mergePredicate(other.getPredicate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor m =
                    input.readMessage(
                        io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.parser(),
                        extensionRegistry);
                if (subjectBuilder_ == null) {
                  ensureSubjectIsMutable();
                  subject_.add(m);
                } else {
                  subjectBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 26: {
                predicateType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getPredicateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * Expected to always be "https://in-toto.io/Statement/v1"
       * </pre>
       *
       * <code>string type = 1 [json_name = "_type"];</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Expected to always be "https://in-toto.io/Statement/v1"
       * </pre>
       *
       * <code>string type = 1 [json_name = "_type"];</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Expected to always be "https://in-toto.io/Statement/v1"
       * </pre>
       *
       * <code>string type = 1 [json_name = "_type"];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Expected to always be "https://in-toto.io/Statement/v1"
       * </pre>
       *
       * <code>string type = 1 [json_name = "_type"];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Expected to always be "https://in-toto.io/Statement/v1"
       * </pre>
       *
       * <code>string type = 1 [json_name = "_type"];</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor> subject_ =
        java.util.Collections.emptyList();
      private void ensureSubjectIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          subject_ = new java.util.ArrayList<io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor>(subject_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> subjectBuilder_;

      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public java.util.List<io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor> getSubjectList() {
        if (subjectBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subject_);
        } else {
          return subjectBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public int getSubjectCount() {
        if (subjectBuilder_ == null) {
          return subject_.size();
        } else {
          return subjectBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor getSubject(int index) {
        if (subjectBuilder_ == null) {
          return subject_.get(index);
        } else {
          return subjectBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder setSubject(
          int index, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (subjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectIsMutable();
          subject_.set(index, value);
          onChanged();
        } else {
          subjectBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder setSubject(
          int index, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder builderForValue) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          subject_.set(index, builderForValue.build());
          onChanged();
        } else {
          subjectBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder addSubject(io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (subjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectIsMutable();
          subject_.add(value);
          onChanged();
        } else {
          subjectBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder addSubject(
          int index, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor value) {
        if (subjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubjectIsMutable();
          subject_.add(index, value);
          onChanged();
        } else {
          subjectBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder addSubject(
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder builderForValue) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          subject_.add(builderForValue.build());
          onChanged();
        } else {
          subjectBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder addSubject(
          int index, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder builderForValue) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          subject_.add(index, builderForValue.build());
          onChanged();
        } else {
          subjectBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder addAllSubject(
          java.lang.Iterable<? extends io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor> values) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subject_);
          onChanged();
        } else {
          subjectBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder clearSubject() {
        if (subjectBuilder_ == null) {
          subject_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          subjectBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public Builder removeSubject(int index) {
        if (subjectBuilder_ == null) {
          ensureSubjectIsMutable();
          subject_.remove(index);
          onChanged();
        } else {
          subjectBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder getSubjectBuilder(
          int index) {
        return getSubjectFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder getSubjectOrBuilder(
          int index) {
        if (subjectBuilder_ == null) {
          return subject_.get(index);  } else {
          return subjectBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public java.util.List<? extends io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> 
           getSubjectOrBuilderList() {
        if (subjectBuilder_ != null) {
          return subjectBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subject_);
        }
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder addSubjectBuilder() {
        return getSubjectFieldBuilder().addBuilder(
            io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder addSubjectBuilder(
          int index) {
        return getSubjectFieldBuilder().addBuilder(
            index, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.getDefaultInstance());
      }
      /**
       * <code>repeated .in_toto_attestation.v1.ResourceDescriptor subject = 2;</code>
       */
      public java.util.List<io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder> 
           getSubjectBuilderList() {
        return getSubjectFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder> 
          getSubjectFieldBuilder() {
        if (subjectBuilder_ == null) {
          subjectBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptor.Builder, io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.ResourceDescriptorOrBuilder>(
                  subject_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          subject_ = null;
        }
        return subjectBuilder_;
      }

      private java.lang.Object predicateType_ = "";
      /**
       * <code>string predicate_type = 3;</code>
       * @return The predicateType.
       */
      public java.lang.String getPredicateType() {
        java.lang.Object ref = predicateType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          predicateType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string predicate_type = 3;</code>
       * @return The bytes for predicateType.
       */
      public com.google.protobuf.ByteString
          getPredicateTypeBytes() {
        java.lang.Object ref = predicateType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          predicateType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string predicate_type = 3;</code>
       * @param value The predicateType to set.
       * @return This builder for chaining.
       */
      public Builder setPredicateType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        predicateType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string predicate_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPredicateType() {
        predicateType_ = getDefaultInstance().getPredicateType();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string predicate_type = 3;</code>
       * @param value The bytes for predicateType to set.
       * @return This builder for chaining.
       */
      public Builder setPredicateTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        predicateType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.Struct predicate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> predicateBuilder_;
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       * @return Whether the predicate field is set.
       */
      public boolean hasPredicate() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       * @return The predicate.
       */
      public com.google.protobuf.Struct getPredicate() {
        if (predicateBuilder_ == null) {
          return predicate_ == null ? com.google.protobuf.Struct.getDefaultInstance() : predicate_;
        } else {
          return predicateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       */
      public Builder setPredicate(com.google.protobuf.Struct value) {
        if (predicateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          predicate_ = value;
        } else {
          predicateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       */
      public Builder setPredicate(
          com.google.protobuf.Struct.Builder builderForValue) {
        if (predicateBuilder_ == null) {
          predicate_ = builderForValue.build();
        } else {
          predicateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       */
      public Builder mergePredicate(com.google.protobuf.Struct value) {
        if (predicateBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            predicate_ != null &&
            predicate_ != com.google.protobuf.Struct.getDefaultInstance()) {
            getPredicateBuilder().mergeFrom(value);
          } else {
            predicate_ = value;
          }
        } else {
          predicateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       */
      public Builder clearPredicate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        predicate_ = null;
        if (predicateBuilder_ != null) {
          predicateBuilder_.dispose();
          predicateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       */
      public com.google.protobuf.Struct.Builder getPredicateBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getPredicateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       */
      public com.google.protobuf.StructOrBuilder getPredicateOrBuilder() {
        if (predicateBuilder_ != null) {
          return predicateBuilder_.getMessageOrBuilder();
        } else {
          return predicate_ == null ?
              com.google.protobuf.Struct.getDefaultInstance() : predicate_;
        }
      }
      /**
       * <code>.google.protobuf.Struct predicate = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
          getPredicateFieldBuilder() {
        if (predicateBuilder_ == null) {
          predicateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                  getPredicate(),
                  getParentForChildren(),
                  isClean());
          predicate_ = null;
        }
        return predicateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:in_toto_attestation.v1.Statement)
    }

    // @@protoc_insertion_point(class_scope:in_toto_attestation.v1.Statement)
    private static final io.github.intoto.attestation.v1.StatementOuterClass.Statement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.intoto.attestation.v1.StatementOuterClass.Statement();
    }

    public static io.github.intoto.attestation.v1.StatementOuterClass.Statement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Statement>
        PARSER = new com.google.protobuf.AbstractParser<Statement>() {
      @java.lang.Override
      public Statement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Statement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Statement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.intoto.attestation.v1.StatementOuterClass.Statement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_in_toto_attestation_v1_Statement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_in_toto_attestation_v1_Statement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&in_toto_attestation/v1/statement.proto" +
      "\022\026in_toto_attestation.v1\032\034google/protobu" +
      "f/struct.proto\0320in_toto_attestation/v1/r" +
      "esource_descriptor.proto\"\241\001\n\tStatement\022\023" +
      "\n\004type\030\001 \001(\tR\005_type\022;\n\007subject\030\002 \003(\0132*.i" +
      "n_toto_attestation.v1.ResourceDescriptor" +
      "\022\026\n\016predicate_type\030\003 \001(\t\022*\n\tpredicate\030\004 " +
      "\001(\0132\027.google.protobuf.StructBG\n\037io.githu" +
      "b.intoto.attestation.v1Z$github.com/in-t" +
      "oto/attestation/go/v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.getDescriptor(),
        });
    internal_static_in_toto_attestation_v1_Statement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_in_toto_attestation_v1_Statement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_in_toto_attestation_v1_Statement_descriptor,
        new java.lang.String[] { "Type", "Subject", "PredicateType", "Predicate", });
    com.google.protobuf.StructProto.getDescriptor();
    io.github.intoto.attestation.v1.ResourceDescriptorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
