// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.24.4
// source: in_toto_attestation/predicates/link/v0/link.proto

package v0

import (
	v1 "github.com/in-toto/attestation/go/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Link struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       []string                 `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Materials     []*v1.ResourceDescriptor `protobuf:"bytes,3,rep,name=materials,proto3" json:"materials,omitempty"`
	Byproducts    *structpb.Struct         `protobuf:"bytes,4,opt,name=byproducts,proto3" json:"byproducts,omitempty"`
	Environment   *structpb.Struct         `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_in_toto_attestation_predicates_link_v0_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_in_toto_attestation_predicates_link_v0_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_in_toto_attestation_predicates_link_v0_link_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Link) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Link) GetMaterials() []*v1.ResourceDescriptor {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *Link) GetByproducts() *structpb.Struct {
	if x != nil {
		return x.Byproducts
	}
	return nil
}

func (x *Link) GetEnvironment() *structpb.Struct {
	if x != nil {
		return x.Environment
	}
	return nil
}

var File_in_toto_attestation_predicates_link_v0_link_proto protoreflect.FileDescriptor

const file_in_toto_attestation_predicates_link_v0_link_proto_rawDesc = "" +
	"\n" +
	"1in_toto_attestation/predicates/link/v0/link.proto\x12&in_toto_attestation.predicates.link.v0\x1a0in_toto_attestation/v1/resource_descriptor.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf2\x01\n" +
	"\x04Link\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12H\n" +
	"\tmaterials\x18\x03 \x03(\v2*.in_toto_attestation.v1.ResourceDescriptorR\tmaterials\x127\n" +
	"\n" +
	"byproducts\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"byproducts\x129\n" +
	"\venvironment\x18\x05 \x01(\v2\x17.google.protobuf.StructR\venvironmentBg\n" +
	"/io.github.intoto.attestation.predicates.link.v0Z4github.com/in-toto/attestation/go/predicates/link/v0b\x06proto3"

var (
	file_in_toto_attestation_predicates_link_v0_link_proto_rawDescOnce sync.Once
	file_in_toto_attestation_predicates_link_v0_link_proto_rawDescData []byte
)

func file_in_toto_attestation_predicates_link_v0_link_proto_rawDescGZIP() []byte {
	file_in_toto_attestation_predicates_link_v0_link_proto_rawDescOnce.Do(func() {
		file_in_toto_attestation_predicates_link_v0_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_in_toto_attestation_predicates_link_v0_link_proto_rawDesc), len(file_in_toto_attestation_predicates_link_v0_link_proto_rawDesc)))
	})
	return file_in_toto_attestation_predicates_link_v0_link_proto_rawDescData
}

var file_in_toto_attestation_predicates_link_v0_link_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_in_toto_attestation_predicates_link_v0_link_proto_goTypes = []any{
	(*Link)(nil),                  // 0: in_toto_attestation.predicates.link.v0.Link
	(*v1.ResourceDescriptor)(nil), // 1: in_toto_attestation.v1.ResourceDescriptor
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
}
var file_in_toto_attestation_predicates_link_v0_link_proto_depIdxs = []int32{
	1, // 0: in_toto_attestation.predicates.link.v0.Link.materials:type_name -> in_toto_attestation.v1.ResourceDescriptor
	2, // 1: in_toto_attestation.predicates.link.v0.Link.byproducts:type_name -> google.protobuf.Struct
	2, // 2: in_toto_attestation.predicates.link.v0.Link.environment:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_in_toto_attestation_predicates_link_v0_link_proto_init() }
func file_in_toto_attestation_predicates_link_v0_link_proto_init() {
	if File_in_toto_attestation_predicates_link_v0_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_in_toto_attestation_predicates_link_v0_link_proto_rawDesc), len(file_in_toto_attestation_predicates_link_v0_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_in_toto_attestation_predicates_link_v0_link_proto_goTypes,
		DependencyIndexes: file_in_toto_attestation_predicates_link_v0_link_proto_depIdxs,
		MessageInfos:      file_in_toto_attestation_predicates_link_v0_link_proto_msgTypes,
	}.Build()
	File_in_toto_attestation_predicates_link_v0_link_proto = out.File
	file_in_toto_attestation_predicates_link_v0_link_proto_goTypes = nil
	file_in_toto_attestation_predicates_link_v0_link_proto_depIdxs = nil
}
