# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: in_toto_attestation/predicates/svr/v0.1/svr.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n1in_toto_attestation/predicates/svr/v0.1/svr.proto\x12'in_toto_attestation.predicates.svr.v0_1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x99\x02\n\x18SimpleVerificationResult\x12\\\n\x08verifier\x18\x01 \x01(\x0b\x32J.in_toto_attestation.predicates.svr.v0_1.SimpleVerificationResult.Verifier\x12=\n\x0ctime_created\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0btimeCreated\x12\x12\n\nproperties\x18\x03 \x03(\t\x1aL\n\x08Verifier\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x06policy\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x42\t\n\x07_policyBg\n/io.github.intoto.attestation.predicates.svr.v01Z4github.com/in-toto/attestation/go/predicates/svr/v01b\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "in_toto_attestation.predicates.svr.v0.1.svr_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n/io.github.intoto.attestation.predicates.svr.v01Z4github.com/in-toto/attestation/go/predicates/svr/v01"
    _globals["_SIMPLEVERIFICATIONRESULT"]._serialized_start = 155
    _globals["_SIMPLEVERIFICATIONRESULT"]._serialized_end = 436
    _globals["_SIMPLEVERIFICATIONRESULT_VERIFIER"]._serialized_start = 360
    _globals["_SIMPLEVERIFICATIONRESULT_VERIFIER"]._serialized_end = 436
# @@protoc_insertion_point(module_scope)
